version: "3"
services:
  server:
    restart: always
    build: .
    environment:
      - HTTP_PORT=${SERVER_HTTP_PORT}
      - HTTPS_PORT=${SERVER_HTTPS_PORT}
      - DB_HOST=db
      - DB_PORT=${DB_INTERNAL_PORT}
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - JWT_SECRET
      - ADMIN_EMAIL
      - ADMIN_DEFAULT_PASSWORD
    expose:
      - ${SERVER_HTTP_PORT}
      - ${SERVER_HTTPS_PORT}
    ports:
      - "${SERVER_HTTP_PORT}:${SERVER_HTTP_PORT}"
      - "${SERVER_HTTPS_PORT}:${SERVER_HTTPS_PORT}"
    command: node server.js
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
volumes:
  db-volume:
