version: "3"
services:
  server:
    restart: always
    build: .
    volumes:
      - ./server:/server/server
    environment:
      - PORT=${SERVER_PORT}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_INTERNAL_PORT}/${DB_NAME}
      - JWT_SECRET
      - ADMIN_EMAIL
      - ADMIN_DEFAULT_PASSWORD
      - LOAD_TEST_SIZE=${LOAD_TEST_SIZE}
      - NODE_ENV=development
    expose:
      - ${SERVER_PORT}
      - ${SERVER_DEBUG_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SERVER_DEBUG_PORT}:${SERVER_DEBUG_PORT}"
    command: node_modules/.bin/nodemon --inspect=0.0.0.0:${SERVER_DEBUG_PORT}
    depends_on:
      - db
  client:
    restart: always
    build: ./client
    volumes:
      - ./client/src:/client/src
    environment:
      - PORT=${CLIENT_PORT}
      - REACT_APP_ENDPOINT=http://localhost:${SERVER_PORT}
      - NODE_ENV=development
    expose:
      - ${CLIENT_PORT}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    command: npm run start
    depends_on:
      - server
  db:
    image: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
volumes:
  db-volume:
